name: Notion Synchronization

on:
  issues:
    types:
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  synchronize-with-notion:
    name: Synchronize with notion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new page on notion
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "parent": {
                "database_id": "${{ secrets.NOTION_DATABASE_ID }}"
              },
              "properties": {
                "Status": {
                  "select": {
                    "name": "Opened"
                  }
                },
                "Title": {
                  "title": [
                    {
                      "text": {
                        "content": "${{ github.event.issue.title }}"  
                      }
                    }  
                  ]    
                },
                "Link": {
                  "url": "${{ github.event.issue.html_url }}"    
                }
              }
            }'
